version: 1.15.{build}
image: Visual Studio 2017
install:
build_script:
- ps: .\build.ps1 -configuration release
artifacts:
- path: bin
  name: Nefarius.ViGEmClient
deploy:
- provider: Environment
  name: BUILDBOT